### ISSUE TITLE
Any possible workaround for the 72hr workflow limit ?

### ISSUE THREAD

**Issue by xd003** [Area69Lab/mirrorbot-workflow#10]
The loop thing surely does help to get around the 6 hr job time limit in github actions but there's a 72 hr workflow level limit too . After 3 days , one would need to recreate a new workflow file to run it , is there any possible way to bypass or get around this limitation ?

**Comment by ElytrA8** [comment]
1 workflow can be extended to 72 hrs
1 job = 6 hr
Every job has its own vm
No other possible way if you don't wanna use loop

**Comment by xd003** [comment]
Thanks for confirmation
